  version: '3'
  services:
    django:
      container_name: nuts_django
      build:
        context: .
      volumes:
        - .:/app
        - nuts_static:/usr/src/app/back_static
        - nuts_media:/usr/src/app/back_media
      restart: always
      depends_on:
        - pgdb
      command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
      ports:
        - "8001:8000"

    pgdb:
      image: postgres:latest
      container_name: nuts_postgres
      restart: always
      environment:
        POSTGRES_DB: ${SQL_DATABASE}
        POSTGRES_USER: ${SQL_USER}
        POSTGRES_PASSWORD: ${SQL_PASSWORD}
      ports:
        - "5433:5432"
      volumes:
        - nuts_db:/var/lib/postgresql/data/

    nginx:
      container_name: nuts_nginx
      image: nginx
      ports:
        - 81:80
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - nuts_static:/usr/src/app/back_static
        - nuts_media:/usr/src/app/back_media
      depends_on:
        - django


  volumes:
    nuts_static:
    nuts_media:
    nuts_db:
